name: Pytorch-vae
channels:
  - pytorch
  - soumith
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cffi=1.11.5=py37h6174b99_1
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.0=118
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.35=ha441bb4_0
  - libtiff=4.0.9=hcb84e12_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37hb8a8100_0
  - mkl_random=1.0.1=py37h5d10147_1
  - ncurses=6.1=h0a44026_0
  - ninja=1.8.2=py37h04f5b5a_1
  - numpy=1.15.4=py37h6a91979_0
  - numpy-base=1.15.4=py37h8a80b8c_0
  - olefile=0.46=py37_0
  - openssl=1.1.1=h1de35cc_0
  - pillow=5.3.0=py37hb68e598_0
  - pip=18.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.1=haf84260_3
  - readline=7.0=h1de35cc_5
  - setuptools=40.5.0=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.25.2=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.32.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pytorch=0.4.1=py37_cuda0.0_cudnn0.0_1
  - torchvision=0.2.1=py37_1
  - pip:
    - click==7.0
    - cycler==0.10.0
    - django==2.1.3
    - dlib==19.16.0
    - face-recognition==1.2.3
    - face-recognition-models==0.3.0
    - image==1.5.27
    - kiwisolver==1.0.1
    - matplotlib==3.0.1
    - opencv-python==3.4.3.18
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - torch==0.4.1
prefix: /Users/macbook/miniconda3/envs/vkhack